CREATE DATABASE IF NOT EXISTS LojaPython;
USE LojaPython;

CREATE TABLE IF NOT EXISTS Cliente(
ID_Cliente INT AUTO_INCREMENT PRIMARY KEY,
Primeiro_Nome VARCHAR(255) NOT NULL,
Ultimo_Nome VARCHAR(255) NOT NULL,
Idade INT NOT NULL,
Sexo CHAR(1) NOT NULL,
Endereco VARCHAR(255) NOT NULL,
Cidade VARCHAR(255) NOT NULL,
Estado CHAR(2) NOT NULL,
Avaliacao INT NOT NULL
);
